services:
  db:
    image: postgres:15
    container_name: marketing_db
    restart: always
    environment:
      POSTGRES_USER: user_marketing
      POSTGRES_PASSWORD: password_influencia
      POSTGRES_DB: marketing_atribucion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
